server:
  port: 9875
spring:
  application:
    name: RHUMAINE-SERVICE
  # MULTIPART (MultipartProperties)
  # Multipart Properties

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

# To disable Hystrix in Feign
feign:
  hystrix:
    enabled: false